version: '3.7'

volumes:
    mysql-data:
        driver: local

services:
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        image: mariadb
        volumes:
            - mysql-data:/var/lib/mysql/data
        restart: always
        ports:
            - "0.0.0.0:43306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pwd123456
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: database

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:alpine
        links:
            - fpm
        ports:
            - "0.0.0.0:45055:80"
        volumes:
            - "./:/var/www"
            - "./docker-compose/nginx/conf.d:/etc/nginx/conf.d"
            - "./docker-compose/nginx/snippets:/nginx/snippets"
    fpm:
        container_name: ${COMPOSE_PROJECT_NAME}_fpm
        build:
            context: docker-compose/73
        working_dir: /var/www
        volumes:
            - "./:/var/www"
