version: '3.7'

volumes:
    db-data:
        driver: local

services:
    postgres:
        container_name: ${COMPOSE_PROJECT_NAME}_pgsql
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pwd123456
            POSTGRES_DB: database
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "0.0.0.0:45432:5432"
        restart: unless-stopped

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:alpine
        links:
            - fpm
        ports:
            - "0.0.0.0:45055:80"
        volumes:
            - "./:/var/www"
            - "./docker-compose/nginx/conf.d:/etc/nginx/conf.d"
            - "./docker-compose/nginx/snippets:/nginx/snippets"
    fpm:
        container_name: ${COMPOSE_PROJECT_NAME}_fpm
        build:
            context: docker-compose/73
        working_dir: /var/www
        volumes:
            - "./:/var/www"
